# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

# Values common to all flavors
sso:
  enabled: true
  existingSecret: vaultwarden-sso
  authority: http://keycloak-http.keycloak.svc.cluster.local:8080/realms/uds
  clientId: 
    value: uds-package-vaultwarden
    existingSecretKey: SSO_CLIENT_SECRET
domain: "vaultwarden.###ZARF_VAR_DOMAIN###"
storage:
  data:
    name: vaultwarden-data
    class: "###ZARF_VAR_STORAGE_CLASS###"
    size: "###ZARF_VAR_STORAGE_SIZE###"
    keepPvc: true
    accessMode: "ReadWriteOnce"

disableAdminToken: true
adminToken:
  value: ""
signupsAllowed: false
image:
  extraVars:
    - key: DISABLE_ADMIN_TOKEN
      value: "true"
    - key: DOMAIN
      value: "https://vaultwarden.###ZARF_VAR_DOMAIN###"
