# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: vaultwarden
  namespace: {{ .Release.Namespace }}
spec:
  adminToken:
    value: {{ .Values.adminToken | quote }}
  sso:
    - name: Vaultwarden Login
      clientId: uds-package-vaultwarden
      redirectUris:
        - "https://vaultwarden.{{ .Values.domain }}/identity/connect/oidc-signin"
      # enableAuthserviceSelector:
      #   app.kubernetes.io/name: vaultwarden
      # groups:
      #   anyOf: ["/UDS Core/Admin"]


      secretName: {{ .Values.sso.secretName }}
      # This secret template configures sso for the application. Will need updated based on application required configuration
      secretTemplate:
        SSO_CLIENT_SECRET: clientField(secret)
        SSO_CLIENT_ID: "clientField(clientId)"
        SSO_AUTHORITY: "https://sso.{{ .Values.domain }}/realms/uds"
        

  # Customize network policies and expose services via istio
  network:
    serviceMesh:
      mode: ambient
    expose:
      - service: vaultwarden
        podLabels:
          app.kubernetes.io/name: vaultwarden
        gateway: tenant
        host: vaultwarden
        port: 80
        targetPort: 8080
    allow:
      - direction: Ingress
        remoteGenerated: IntraNamespace
        port: 8080
        description: "App Internal"

      - direction: Egress
        remoteGenerated: IntraNamespace
        port: 8080
        description: "App Internal"

      - direction: Egress
        remoteNamespace: keycloak
        remoteSelector:
          app.kubernetes.io/name: keycloak
        selector:
          app.kubernetes.io/name: vaultwarden
        port: 8080
        description: "SSO Internal"
      

      - direction: Egress
        remoteNamespace: istio-tenant-gateway
        remoteSelector:
          app: tenant-ingressgateway
        selector:
          app.kubernetes.io/name: vaultwarden
        port: 443
        description: "SSO External"
      # Custom rules for unanticipated scenarios
      {{- with .Values.additionalNetworkAllow }}
      {{ toYaml . | nindent 6 }}
      {{- end }}
